"""auto Add dir column in  vote

Revision ID: ce4b7eb94f87
Revises: 3881bd770c02
Create Date: 2026-10-09 22:33:13.743164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4b7eb94f87'
down_revision: Union[str, Sequence[str], None] = '3881bd770c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('dir', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'dir')
    # ### end Alembic commands ###
